spring:
  # configuration profile
  profiles:
    active: dev
  # configuration thymeleaf template
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html;charset=utf-8
  messages:
    always-use-message-format: false
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization.fail_on_unknown_properties: false
  # configuration database
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.30.55:3306/graduation_design?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

# configuration server
server:
  port: 8080
  servlet:
    context-path: /lilun

# configuration mybatis
mybatis:
  type-aliases-package: com.dl.entity
  config-location: classpath:mappers/**/*.xml

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: gld

---
spring:
  profiles: prod